### ISSUE TITLE
so文件这个问题如何解决？

### ISSUE THREAD

**Issue by qiusunshine** [Justson/AgentWebX5#9]
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit

,,,

at com.just.library.DefaultWebCreator.web(DefaultWebCreator.java:186)
	at com.just.library.DefaultWebCreator.createGroupWithWeb(DefaultWebCreator.java:134)
	at com.just.library.DefaultWebCreator.create(DefaultWebCreator.java:111)
	at com.just.library.DefaultWebCreator.create(DefaultWebCreator.java:23)
	at com.just.library.AgentWeb.<init>(AgentWeb.java:93)
	at com.just.library.AgentWeb.<init>(AgentWeb.java:41)
	at com.just.library.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:498)
	at com.just.library.AgentWeb$AgentBuilder.access$6600(AgentWeb.java:406)
	at com.just.library.AgentWeb$CommonAgentBuilder.createAgentWeb(AgentWeb.java:662)
,,,

**Comment by iielse** [comment]
我也卡到这里了

**Comment by qiusunshine** [comment]
https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/34cf1488-7dc2-41ca-a77f-0014112bcab7
